services:

  laravel-docker:
    container_name: laravel-docker-database
    build: .
    volumes:
      - ./laravel-app:/var/www/html
    ports:
      - 8098:80
  
  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_docker
    ports:
    - 3306:3306
  
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8093:80
    environment:
      - PMA_ARBITRARY=1